services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongodb2:/data/db
