name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: Install PNPM
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
